version: '3.2'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: mongo:4.2
    container_name: mongodb
    networks:
      - graylog
    ports:
      - 27018:27017
    volumes:
      - type: bind
        source: /mnt/graylog/mongodata
        target: /data/db
      - type: bind
        source: /mnt/graylog/mongoconfig
        target: /data/configdb
      - type: bind
        source: /mnt/graylog/logs/mongo
        target: /var/log/mongodb
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - type: bind
        source: /mnt/graylog/elasticdata
        target: /usr/share/elasticsearch/data
      - type: bind
        source: /mnt/graylog/logs/elastic
        target: /var/log/elasticsearch
    networks:
      - graylog
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog-enterprise:4.2.3-arm64
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=1234567890123456
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_ELASTICSEARCH_VERSION=7
      - GRAYLOG_HTTP_ENABLE_CORS=true
      - GRAYLOG_METRICS_PROMETHEUS_ENABLED=true
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      - graylog
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
      # Beats
      - 5044:5044
      - 5044:5044/udp
      - 5045:5045
      - 5045:5045/udp
    volumes:
      - type: bind
        source: /mnt/graylog/journal
        target: /usr/share/graylog/data/journal
      - type: bind
        source: /mnt/graylog/logs/graylog-server
        target: /var/log/graylog-server
      - type: bind
        source: /mnt/graylog/data
        target: /usr/share/graylog/data/geo/
networks:
  graylog:
    driver: bridge
